### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by ai** [nkt/eslint-plugin-es5#1]
We could make docs much better (and promote project):

* Add rules list to `README.md`.
* Add examples, why ES6 code could broke your production (like Safari and `const` problem).

**Comment by nkt** [comment]
@ai thanks for interest =)
I've added docs for each rule.
But I still don't know why you don't want to use babel. For me babel is postcss in JS world.

**Comment by nkt** [comment]
I've added ["Why?"](https://github.com/nkt/eslint-plugin-es5/commit/35e89dc9dd2ecd7ddb5f81df1d10915dd15deac3?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8) section, so I'm closing this.

**Comment by ai** [comment]
Great. Thanks :)
