### ISSUE TITLE
1.4.0 regression on 'es6 functions not allowed'

### ISSUE THREAD

**Issue by richardspence** [nkt/eslint-plugin-es5#31]
This code fails in 1.4.0, but passes in 1.3.x

```js
Foo.prototype.toString = function toString(){...}
```

Cursory glance, it looks like this commit might be the culprit: https://github.com/nkt/eslint-plugin-es5/commit/84504e7162b7b796adbc4e22adf8db9cbb52df28#diff-fc9d2adbd42af3a2b5385af5ab88241a

**Comment by nkt** [comment]
I've reverted this PR. Fix published under 1.4.1.
Thanks!
