### ISSUE TITLE
Add rule/option for only allowing `let` declarations in `for ... in` for IE11

### ISSUE THREAD

**Issue by mfeineis** [nkt/eslint-plugin-es5#33]
First: thank you for this plugin, it's pretty useful. I prefer to use the baseline JavaScript for the legaciest browser I support, i.e. IE11. For keeping my  JS fully IE11 compatible I can disable the `no-block-scope` rule since that is OK most of the time. But it seems that IE11 doesn't like `const` declarations in `for  (const item in items)` loops. It'd  be really cool if this plugin added a rule or expanded the options of the block scoping rule to  (dis-)allow this usage of `const`.  Thanks, again, have a nice day!

**Comment by Sauloxd** [comment]
It seems you could use this plugin combined with this other one: https://github.com/Volox/eslint-plugin-ie11#supported-rules, would be awesome for all rules to be in one plugin though...

**Comment by mfeineis** [comment]
@Sauloxd thanks, that setup works for me.
